version: '3'
services:
  tweetloader:
    build: ./tweetLoader
    env_file: .env
    depends_on:
      - "elastic1"
    command: ["node", "."]
    restart: on-failure
    networks:
      - esnet
  elastic1:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.2.3
    container_name: elastic1
    environment:
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - esdata1:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
    networks:
      - esnet
  elastic2:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.2.3
    container_name: elastic2
    environment:
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - "discovery.zen.ping.unicast.hosts=elastic1"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - esdata2:/usr/share/elasticsearch/data
    networks:
      - esnet
volumes:
  esdata1:
    driver: local
  esdata2:
    driver: local
networks:
  esnet:
